auto_start: true
excluded_tools: []
included_tools:
- find_symbol
- read_file
- execute_shell_command
- list_dir
- get_symbols_overview
- search_for_pattern
project_name: panda-index-helper-mcp
project_settings:
  custom_prompts: []
  language_servers: []
  memory_enabled: true
read_only: false
serena_context: ide-assistant
